dist: xenial

os: linux

language: node_js

node_js:
  - node
  - lts/*
  - 14
  - 13
  - 12
  - 11
  - 10

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_token: ${NPM_API_TOKEN}
  on:
    tags: true
    condition: $TRAVIS_NODE_VERSION = "12"

install:
  - npm install

script:
  - npm run cover

after_success:
  - |
    if [[ $TRAVIS_NODE_VERSION == "12" ]]; then
      cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js;
    fi
