version: "3.8"
services:
  sonarqube:
    image: sonarqube:9.2.4-community
    container_name: npm-pkg-year-interval-sonarqube
    volumes:
      - ./data/sonarqube_conf:/opt/sonarqube/conf
      - ./data/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube_extensions:/opt/sonarqube/extensions
      - ./data/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - "9000:9000"
    networks:
      - npm-pkg-year-interval

  sonarscanner:
    image: sonarsource/sonar-scanner-cli:4.6
    container_name: npm-pkg-year-interval-sonarscanner
    volumes:
      - ./:/usr/src
    environment:
      - SONAR_HOST_URL=${SONAR_HOST_URL}
      - SONAR_LOGIN=${SONAR_TOKEN}
    networks:
      - npm-pkg-year-interval


networks:
  npm-pkg-year-interval:
    name: npm-pkg-year-interval
    driver: bridge 